In [9]:
import  numpy as np
from scipy import sparse

matrix_large= np.array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
[0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
[3, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

matrix_large_sparse = sparse.csr_matrix(matrix_large)
print(matrix_large)
print(matrix_large_sparse)



[[0 0 0 0 0 0 0 0 0 0]
 [0 1 0 0 0 0 0 0 0 0]
 [3 0 0 0 0 0 0 0 0 0]]
  (1, 1)	1
  (2, 0)	3


In [23]:
matrix = np.array([[1,2,3],[4,5,6],[7,8,9]])

matrix.ndim




2

In [66]:
import pandas as pd

url = 'https://stats.govt.nz/assets/Uploads/Annual-enterprise-survey/Annual-enterprise-survey-2021-financial-year-provisional/Download-data/annual-enterprise-survey-2021-financial-year-provisional-size-bands-csv.csv'

dataframe = pd.read_csv(url)

dataframe.groupby('year').head()


year industry_code_ANZSIC               industry_name_ANZSIC  \
0      2011                    A  Agriculture, Forestry and Fishing   
1      2011                    A  Agriculture, Forestry and Fishing   
2      2011                    A  Agriculture, Forestry and Fishing   
3      2011                    A  Agriculture, Forestry and Fishing   
4      2011                    A  Agriculture, Forestry and Fishing   
1548   2012                    A  Agriculture, Forestry and Fishing   
1549   2012                    A  Agriculture, Forestry and Fishing   
1550   2012                    A  Agriculture, Forestry and Fishing   
1551   2012                    A  Agriculture, Forestry and Fishing   
1552   2012                    A  Agriculture, Forestry and Fishing   
3096   2013                    A  Agriculture, Forestry and Fishing   
3097   2013                    A  Agriculture, Forestry and Fishing   
3098   2013                    A  Agriculture, Forestry and Fishing   
3099   2013                    A  Agriculture, Forestry and Fishing   
3100   2013                    A  Agriculture, Forestry and Fishing   
4644   2014                    A  Agriculture, Forestry and Fishing   
4645   2014                    A  Agriculture, Forestry and Fishing   
4646   2014                    A  Agriculture, Forestry and Fishing   
4647   2014                    A  Agriculture, Forestry and Fishing   
4648   2014                    A  Agriculture, Forestry and Fishing   
6192   2015                    A  Agriculture, Forestry and Fishing   
6193   2015                    A  Agriculture, Forestry and Fishing   
6194   2015                    A  Agriculture, Forestry and Fishing   
6195   2015                    A  Agriculture, Forestry and Fishing   
6196   2015                    A  Agriculture, Forestry and Fishing   
7740   2016                    A  Agriculture, Forestry and Fishing   
7741   2016                    A  Agriculture, Forestry and Fishing   
7742   2016                    A  Agriculture, Forestry and Fishing   
7743   2016                    A  Agriculture, Forestry and Fishing   
7744   2016                    A  Agriculture, Forestry and Fishing   
9288   2017                    A  Agriculture, Forestry and Fishing   
9289   2017                    A  Agriculture, Forestry and Fishing   
9290   2017                    A  Agriculture, Forestry and Fishing   
9291   2017                    A  Agriculture, Forestry and Fishing   
9292   2017                    A  Agriculture, Forestry and Fishing   
10836  2018                    A  Agriculture, Forestry and Fishing   
10837  2018                    A  Agriculture, Forestry and Fishing   
10838  2018                    A  Agriculture, Forestry and Fishing   
10839  2018                    A  Agriculture, Forestry and Fishing   
10840  2018                    A  Agriculture, Forestry and Fishing   
12384  2019                    A  Agriculture, Forestry and Fishing   
12385  2019                    A  Agriculture, Forestry and Fishing   
12386  2019                    A  Agriculture, Forestry and Fishing   
12387  2019                    A  Agriculture, Forestry and Fishing   
12388  2019                    A  Agriculture, Forestry and Fishing   
13932  2020                    A  Agriculture, Forestry and Fishing   
13933  2020                    A  Agriculture, Forestry and Fishing   
13934  2020                    A  Agriculture, Forestry and Fishing   
13935  2020                    A  Agriculture, Forestry and Fishing   
13936  2020                    A  Agriculture, Forestry and Fishing   
15480  2021                    A  Agriculture, Forestry and Fishing   
15481  2021                    A  Agriculture, Forestry and Fishing   
15482  2021                    A  Agriculture, Forestry and Fishing   
15483  2021                    A  Agriculture, Forestry and Fishing   
15484  2021                    A  Agriculture, Forestry and Fishing   

      rme_size_grp            

In [65]:
dataframe = pd.DataFrame()
dataframe['Name'] = ['Paul Tergat', 'Madam Neville']
dataframe['Age'] = [34,46]
dataframe['Driver'] = [True, False]

new_person = pd.Series(['Paula Costa',22, False],index=['Name','Age','Driver'])
dataframe.append(new_person, ignore_index=True)


C:\Users\devop\AppData\Local\Temp\ipykernel_5972\2856178613.py:7: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dataframe.append(new_person, ignore_index=True)


KeyError: 'year'

In [68]:
text_data = [
    "  Welcome tday. By Paul Tergat   ",
    "Man always is very helpful. By Peter Dury",
    " Most day of the night. By Janet Jackson"
]

removed_whitespace = [string.strip() for string in text_data]

removed_whitespace
removed_periods = [string.replace(".","") for string in removed_whitespace]
removed_periods


['Welcome tday By Paul Tergat',
 'Man always is very helpful By Peter Dury',
 'Most day of the night By Janet Jackson']

In [73]:
from bs4 import BeautifulSoup

html = """
       <div class='full_name'><span style='font-weight:bold'>
       Masego</span> Azra</div>"
       """
soup = BeautifulSoup(html, "lxml")
soup.find("div",{"class": "full_name"}).text

'\n       Masego Azra'

In [75]:
import unicodedata
import sys

text_data = ['Hi!!!! I. Love. This. Song....',
             '10000% Agree!!!! #LoveIT',
             'Right?!?!']
punctuation = dict.fromkeys(i for i in range(sys.maxunicode)
                            if unicodedata.category(chr(i)).startswith('P'))
[string.translate(punctuation) for string in text_data]


['Hi I Love This Song', '10000 Agree LoveIT', 'Right']

In [78]:
from nltk.corpus import stopwords
tokenized_words= [
    'i', 'am', 'going', 'to', 'go', 'to', 'the', 'store', 'and'
]


stop_words = stopwords.words('english')
[word for word in tokenized_words if word not in stop_words]


['going', 'go', 'store']